---
title: "Generating phenotypic decline indexes using the pdi package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Generating phenotypic decline indexes using the pdi package}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align = 'center'
)
```

## Introduction

Firstly load the package:

```{r library_load,message=FALSE}
library(pdi)
```

Additional packages will also need to be loaded to aid this example:

```{r additional_libraries,message=FALSE}
library(purrr)
library(dplyr)
library(ggplot2)
library(magrittr)
```

## Example Data

For this 
```{r file_paths}
files <- list.files(
  system.file('phenotypeDataCollectionSheets',
              package = 'pdi'),
  full.names = TRUE) 
```

The filenames are shown below:

```{r files}
basename(files)
```
## Index generation

### Data preparation

```{r read_files}
d <- map(files,readPhenotypeSheet)
```

```{r prepare_data}
p <- map(d,preparePhenotypeData) %>%
  bind_rows()
```

```{r data}
p
```

### Site correction

```{r DBH_site_plot}
ggplot(p,aes(x = Location,y = `Diameter at breast height (m)`)) +
  geom_boxplot() +
  theme_bw()
```

```{r site_correction}
sc <- siteCorrection(p)
```

```{r DBH_site_adjusted_plot}
ggplot(sc,aes(x = Location,y = `Diameter at breast height (m)`)) +
  geom_boxplot() +
  theme_bw()
```

### Additional descriptors calculation

```{r additional_descriptors}
a <- sc %>%
  mutate(`Live crown ratio (%)` = liveCrownRatio(`Total height (m)`,
                                                 `Lower crown height (m)`),
         `Crown condition (%)` = crownCondition(`Missing crown (%)`,
                                                `Crown transparency (%)`),
         `Crown volume (m^3)` = crownVolume(`Crown radius (m)`,
                                            `Total height (m)`,
                                            `Lower crown height (m)`,
                                            `Crown condition (%)`),
         `Bleed prevalence (%)` = bleedPrevalence(`Active bleed length (mm)`,
                                                  `Active bleeds`,
                                                  `Black staining length (mm)`,
                                                  `Black staining`,
                                                  `Diameter at breast height (m)`),
         `Agrilus exit hole density (m^-2)` = agrilusExitHoleDensity(`Agrilus exit holes`,`Diameter at breast height (m)`)
  )
```

### Random forest
```{r prepare_data_for_rf}
t <- makeAnalysisTable(a)
```

```{r random_forest}
m <- rf(t,cls = NULL,nreps = 10)
```

### Index calculation

```{r calculate_DIs}
DIs <- calcDIs(m,invertPDI = FALSE,invertDAI = FALSE) %>%
  bind_cols(a %>%
              select(Location,ID,Status))
```

```{r,fig.width=8}
ggplot(DIs,aes(x = PDI,y = DAI,colour = Status)) +
  geom_point() +
  theme_bw() +
  facet_wrap(~Location)
```

